### ISSUE TITLE
Request: Line Numbers for Errors

### ISSUE THREAD

**Issue by abgier-avraha** [Place1/openapi-linter#2]
I'll get an error like `error "" parameter "" must follow the SnakeCase naming convention` and I understand that the errors are printed out sequentially but it would be helpful to just include the line number where the error originates.

**Comment by Place1** [comment]
yep i'm planning to add this feature. currently it's a little difficult because the implementation is basically just checking rules against an in memory object (the spec) which is created by unmarshalling the raw json/yaml spec file. Currently this unmarshalling doesn't leave me with any file markers to indicate start/end positions for keys/properties in the object (spec). I'm searching for a solution though :smile:

**Comment by Place1** [comment]
@rmit-s3539777-abgier-avraha i've addressed this issue in v0.0.4 by making sure each error includes a json ref to the relevant part of the spec. the errors are sorted by this ref in the output as well.
